language: cpp

os: 
    - osx
    - linux 

env:
    matrix:
        - TEST_SUITE="bin/py.test -n 2 -vvs --ignore=tests/scancode --ignore=tests/extractcode --ignore=tests/licensedcode --ignore=tests/cluecode --ignore=tests/packagedcode"
        - TEST_SUITE="bin/py.test -n 2 -vvs tests/scancode"
        - TEST_SUITE="bin/py.test -n 2 -vvs tests/extractcode"
        - TEST_SUITE="bin/py.test -n 2 -s tests/licensedcode"
        - TEST_SUITE="bin/py.test -n 2 -s tests/cluecode"
        - TEST_SUITE="bin/py.test -n 2 -s tests/packagedcode"
        - TEST_SUITE="./etc/release/release.sh"


install:
    - ./configure

script:
    - $TEST_SUITE

notifications:
    irc:
        channels:
          - "chat.freenode.net#aboutcode"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
    template:
        - "%{repository_slug}#%{build_number} (%{branch}-%{commit}:%{author})-%{message}- %{build_url}"
        - 
        - 
